FROM amazoncorretto:21-alpine-jdk AS builder
COPY ./src/demo /app
# WORKDIR /app
# RUN ./gradlew build
# FROM adoptopenjdk/openjdk11:debianslim-jre
# COPY --from=builder /tmp/target/app.jar /app/app.jar
# ENTRYPOINT ["java", "-jar", "app.jar"]
