version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/app/DockerfileDevelop
    volumes:
      - ./src/demo:/app
    ports:
      - 8080:8080
    tty: true
    env_file:
      - ./env_file_develop

networks:
  default:
    name: dynamodb-local
    external: true
